name: trial-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # Core libraries
  - numpy
  - pandas
  # Image processing libraries
  - scikit-image
  - scipy
  - matplotlib
  - seaborn
  - opencv 
  # .nd2 file handling
  - nd2  # Install nd2 from conda-forge
  - nd2reader  # Install nd2 from conda-forge
  # Jupyter and related tools
  - jupyterlab
  - ipykernel
  - stackview
  # Plotting libraries
  - plotly
   # Optional libraries
   - argparse 
   - python-tk 
